# https://github.com/actions/checkout/issues/165#issuecomment-657673315
name: Checkout with LFS caching
runs:
  using: composite
  steps:
  - name: Checkout code
    uses: actions/checkout@v2

  - name: Create LFS file list
    run: |
      git lfs ls-files -l | cut -d ' ' -f1 | sort >.git/lfs-files.tmp
    shell: bash

  - name: Restore LFS cache
    uses: actions/cache@v2
    id: lfs-cache
    with:
      path: .git/lfs
      key: ${{ runner.os }}-lfs-${{ hashFiles('.git/lfs-files.tmp') }}-v1

  - name: Pull LFS blobs
    run: |
      git lfs pull
    shell: bash
